version: '3.3'
services:
    acessivel:
        init: true
        container_name: acessivel
        image: acessivel:latest
        restart: unless-stopped
        environment:
            MASTODON_KEY: <insira aqui>
            INSTANCE_URL: <insira aqui>
            INSTANCE_NAME: <insira aqui>
            DM_MSG: "Alto lá! :policia: \\n\\nCom licença, @$${post.user.userName}.\\n\\nReparei que este post ($${post.url}) tem uma imagem ou vídeo sem descrição. Como na $${process.env.INSTANCE_NAME} temos muito apreço por abrir as portas e incluir pessoas com deficiência visual, gostaria de reforçar com você este acordo de acessibilidade.\\n\\nPor favor, veja se é possível revisar e editar seu toot (via app ou web), adicionando descrição nas mídias.\\n\\nMuito obrigado por sua compreensão e apoio!"
            NODE_ENV: production
        volumes:
            - /data/acessivel:/usr/app/acessivel/dist